// Code generated by "stringer -type=InstKind -trimprefix=Inst"; DO NOT EDIT.

package ir

import "strconv"

const _InstKind_name = "InvalidIloadRetIretLretCallStaticCallGoIcmpLcmpJumpJumpEqualJumpNotEqualJumpGtEqIaddLaddFaddIsubInegLnegDaddConvL2IConvF2IConvD2I"

var _InstKind_index = [...]uint8{0, 7, 12, 15, 19, 23, 33, 39, 43, 47, 51, 60, 72, 80, 84, 88, 92, 96, 100, 104, 108, 115, 122, 129}

func (i InstKind) String() string {
	if i < 0 || i >= InstKind(len(_InstKind_index)-1) {
		return "InstKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstKind_name[_InstKind_index[i]:_InstKind_index[i+1]]
}
