// Code generated by "stringer -type=Op -linecomment=true"; DO NOT EDIT.

package bytecode

import "strconv"

const (
	_Op_name_0 = "nopaconst_nulliconst_m1iconst_0iconst_1iconst_2iconst_3iconst_4iconst_5lconst_0lconst_1fconst_0fconst_1fconst_2dconst_0dconst_1bipushsipushldcldc_wldc2_wiloadlloadfloaddloadaloadiload_0iload_1iload_2iload_3lload_0lload_1lload_2lload_3fload_0fload_1fload_2fload_3dload_0dload_1dload_2dload_3aload_0aload_1aload_2aload_3ialoadlaloadfaloaddaloadaaloadbaloadcaloadsaloadistorelstorefstoredstoreastoreistore_0istore_1istore_2istore_3lstore_0lstore_1lstore_2lstore_3fstore_0fstore_1fstore_2fstore_3dstore_0dstore_1dstore_2dstore_3astore_0astore_1astore_2astore_3iastorelastorefastoredastoreaastorebastorecastoresastorepoppop2dupdup_x1dup_x2dup2dup2_x1dup2_x2swapiaddladdfadddaddisublsubfsubdsubimullmulfmuldmulidivldivfdivddiviremlremfremdremineglnegfnegdnegishllshlishrlshriushrlushriandlandiorlorixorlxoriinci2li2fi2dl2il2fl2df2if2lf2dd2id2ld2fi2bi2ci2slcmpfcmplfcmpgdcmpldcmpgifeqifneifltifgeifgtifleif_icmpeqif_icmpneif_icmpltif_icmpgeif_icmpgtif_icmpleif_acmpeqif_acmpnegotojsrret"
	_Op_name_1 = "ireturnlreturnfreturndreturnareturnreturngetstaticputstaticgetfieldputfieldinvokevirtualinvokespecialinvokestaticinvokeinterfaceinvokedynamicnewnewarrayanewarrayarraylengthathrowcheckcastinstanceofmonitorentermonitorexit"
	_Op_name_2 = "multianewarrayifnullifnonnullgoto_wjsr_wbreakpoint"
	_Op_name_3 = "impdep1impdep2"
)

var (
	_Op_index_0 = [...]uint16{0, 3, 14, 23, 31, 39, 47, 55, 63, 71, 79, 87, 95, 103, 111, 119, 127, 133, 139, 142, 147, 153, 158, 163, 168, 173, 178, 185, 192, 199, 206, 213, 220, 227, 234, 241, 248, 255, 262, 269, 276, 283, 290, 297, 304, 311, 318, 324, 330, 336, 342, 348, 354, 360, 366, 372, 378, 384, 390, 396, 404, 412, 420, 428, 436, 444, 452, 460, 468, 476, 484, 492, 500, 508, 516, 524, 532, 540, 548, 556, 563, 570, 577, 584, 591, 598, 605, 612, 615, 619, 622, 628, 634, 638, 645, 652, 656, 660, 664, 668, 672, 676, 680, 684, 688, 692, 696, 700, 704, 708, 712, 716, 720, 724, 728, 732, 736, 740, 744, 748, 752, 756, 760, 764, 768, 773, 778, 782, 786, 789, 792, 796, 800, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837, 840, 843, 846, 849, 853, 858, 863, 868, 873, 877, 881, 885, 889, 893, 897, 906, 915, 924, 933, 942, 951, 960, 969, 973, 976, 979}
	_Op_index_1 = [...]uint8{0, 7, 14, 21, 28, 35, 41, 50, 59, 67, 75, 88, 101, 113, 128, 141, 144, 152, 161, 172, 178, 187, 197, 209, 220}
	_Op_index_2 = [...]uint8{0, 14, 20, 29, 35, 40, 50}
	_Op_index_3 = [...]uint8{0, 7, 14}
)

func (i Op) String() string {
	switch {
	case 0 <= i && i <= 169:
		return _Op_name_0[_Op_index_0[i]:_Op_index_0[i+1]]
	case 172 <= i && i <= 195:
		i -= 172
		return _Op_name_1[_Op_index_1[i]:_Op_index_1[i+1]]
	case 197 <= i && i <= 202:
		i -= 197
		return _Op_name_2[_Op_index_2[i]:_Op_index_2[i+1]]
	case 254 <= i && i <= 255:
		i -= 254
		return _Op_name_3[_Op_index_3[i]:_Op_index_3[i+1]]
	default:
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
